time: 2014-01-06 11:17:58.051445Z
tags: worker-0
test: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume]
time: 2014-01-06 11:18:07.661621Z
failure: tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
186
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 187, in test_volume_boot_pattern
    volume_origin = self._create_volume_from_image(self.image)
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 86, in _create_volume_from_image
    img_uuid = image.id
NameError: global name 'image' is not defined
0
]
tags: -worker-0
