time: 2014-01-09 09:55:46.560363Z
tags: worker-0
test: tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario[compute,image,network,volume]
time: 2014-01-09 10:01:32.069969Z
failure: tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario[compute,image,network,volume] [ multipart
Content-Type: text/plain;charset="utf8"
pythonlogging:''
0
Content-Type: text/plain;charset="utf8"
stderr
0
Content-Type: text/plain;charset="utf8"
stdout
0
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
52F
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 184, in test_minimum_basic_scenario
    self.nova_volume_detach()
  File "/home/os1/tempest/tempest/scenario/test_minimum_basic.py", line 157, in nova_volume_detach
    detach_volume_client(self.server.id, self.volume.id)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/volumes.py", line 165, in delete_server_volume
    (server_id, attachment_id,))
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 154, in _delete
    _resp, _body = self.api.client.delete(url)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 238, in delete
    return self._cs_request(url, 'DELETE', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 213, in _cs_request
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 195, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 189, in request
    raise exceptions.from_response(resp, body, url, method)
ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-efb2fffd-8596-46d9-9787-0a1d9ad2b980)
0
]
tags: -worker-0
time: 2014-01-09 10:01:51.607498Z
tags: worker-0
test: tearDownClass (tempest.scenario.test_minimum_basic.TestMinimumBasicScenario)
time: 2014-01-09 10:01:51.607498Z
failure: tearDownClass (tempest.scenario.test_minimum_basic.TestMinimumBasicScenario) [ multipart
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
519
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/manager.py", line 248, in tearDownClass
    thing.delete()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/security_group_rules.py", line 29, in delete
    self.manager.delete(self)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/security_group_rules.py", line 77, in delete
    self._delete('/os-security-group-rules/%s' % base.getid(rule))
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 154, in _delete
    _resp, _body = self.api.client.delete(url)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 238, in delete
    return self._cs_request(url, 'DELETE', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 213, in _cs_request
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 195, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 189, in request
    raise exceptions.from_response(resp, body, url, method)
ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-933b4b35-4fb8-4a94-a579-24b4b49bc080)
0
]
tags: -worker-0
time: 2014-01-09 10:01:51.700561Z
tags: worker-0
test: process-returncode
time: 2014-01-09 10:01:51.700561Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
